Check [WILDCARD]/test/exit_sanitizer.ts
running 3 tests from [WILDCARD]/test/exit_sanitizer.ts
test exit(0) ... FAILED ([WILDCARD])
test exit(1) ... FAILED ([WILDCARD])
test exit(2) ... FAILED ([WILDCARD])

failures:

exit(0)
AssertionError: Test case attempted to exit with exit code: 0
    at [WILDCARD]
    at [WILDCARD]/test/exit_sanitizer.ts:2:8
    at [WILDCARD]

exit(1)
AssertionError: Test case attempted to exit with exit code: 1
    at [WILDCARD]
    at [WILDCARD]/test/exit_sanitizer.ts:6:8
    at [WILDCARD]

exit(2)
AssertionError: Test case attempted to exit with exit code: 2
    at [WILDCARD]
    at [WILDCARD]/test/exit_sanitizer.ts:10:8
    at [WILDCARD]

failures:

	exit(0)
	exit(1)
	exit(2)

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out ([WILDCARD])

error: Test failed
